# Generated by Django 4.1.5 on 2023-01-31 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('TicketId', models.AutoField(primary_key=True, serialize=False)),
                ('TicketDescription', models.CharField(max_length=255)),
                ('TicketStatus', models.CharField(max_length=16)),
                ('TicketPriority', models.CharField(max_length=16)),
                ('TicketAssigned', models.CharField(max_length=30)),
                ('TicketPoints', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
