# Generated by Django 4.1.5 on 2023-01-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=30)),
                ('ProjectDescription', models.CharField(max_length=200)),
                ('ProjectStatus', models.CharField(choices=[('FI', 'Finished'), ('IP', 'InProgress'), ('CU', 'Coming Up')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=26)),
                ('UserEmail', models.EmailField(max_length=60)),
                ('UserPassword', models.CharField(max_length=16)),
                ('UserPoints', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='TicketAssigned',
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketAssignedTo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='TicketPriority',
            field=models.CharField(choices=[('VH', 'Very Important'), ('H', 'Important'), ('M', 'Medium'), ('L', 'Low')], max_length=16),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='TicketStatus',
            field=models.CharField(choices=[('OP', 'Open'), ('PE', 'Pending'), ('CL', 'Closed')], max_length=20),
        ),
    ]
