# Generated by Django 4.1.5 on 2023-01-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_project_user_remove_ticket_ticketassigned_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='DevUser',
        ),
    ]
