# Generated by Django 4.1.5 on 2023-01-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_devuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='devuser',
            name='UserRole',
            field=models.TextField(choices=[('DEV', 'Developer'), ('SEN', 'Senior')], max_length=12, null=True),
        ),
    ]
