# Generated by Django 4.1.5 on 2023-01-31 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_devuser_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='devuser',
            name='Project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.project'),
        ),
    ]
