# Generated by Django 4.1.5 on 2023-01-31 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_devuser_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devuser',
            name='Project',
        ),
        migrations.AddField(
            model_name='devuser',
            name='UserProject',
            field=models.ManyToManyField(to='accounts.project'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketProject',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.devuser'),
        ),
    ]
