# Generated by Django 4.1.5 on 2023-01-31 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_ticket_ticketuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='TicketUser',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='TicketAssignedTo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.devuser'),
        ),
    ]
