# Generated by Django 4.1.5 on 2023-02-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_ticket_ticketpriority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='TicketSubmittedBy',
            field=models.CharField(default='ahmed', max_length=26),
            preserve_default=False,
        ),
    ]
