# Generated by Django 4.1.5 on 2023-02-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_ticket_ticketsubmittedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devuser',
            name='UserProject',
            field=models.ManyToManyField(blank=True, to='accounts.project'),
        ),
    ]
