# Generated by Django 4.1.5 on 2023-02-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_devuser_userproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='TicketAssignedTo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignedto', to='accounts.devuser'),
        ),
    ]
