# Generated by Django 4.1.5 on 2023-02-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_ticket_ticketassignedto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='TicketAssignedTo',
            new_name='ticketassignedto',
        ),
    ]
