# Generated by Django 4.1.5 on 2023-02-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_devuser_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devuser',
            name='UserRole',
            field=models.TextField(choices=[('Developer', 'DEV'), ('Senior', 'SEN'), ('Admin', 'ADM')], max_length=12, null=True),
        ),
    ]
